### ISSUE TITLE
Invalid string length error

### ISSUE THREAD

**Issue by jcollum** [wdavidw/node-csv-stringify#43]
```
Debug: internal, implementation, error 
    RangeError: Invalid string length
    at Array.join (native)
    at null.<anonymous> (/Users/collumj/work/crdb/xxx-xxxx-utilities/node_modules/csv-stringify/lib/index.js:64:36)
    at emitNone (events.js:72:20)
    at emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
```

It does seem relevant to your library though, since other people may run into this issue. The solution was to pull in fewer records  from SQL before stringifying them.

**Comment by slaughtr** [comment]
I've been having a similar (or possibly the same?) issue somewhat randomly with this library as of late:

`/Users/slaughtr/Desktop/blah/blahblah/blah/node_modules/csv-stringify/lib/index.js:77
      return callback(null, chunks.join(''));
                                   ^

RangeError: Invalid string length
    at Array.join (native)
    at Stringifier.<anonymous> (/Users/slaughtr/Desktop/blah/blahblah/blah/node_modules/csv-stringify/lib/index.js:77:36)
    at emitNone (events.js:91:20)
    at Stringifier.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)`

It seems (as the OP here said over a year ago), that I just need to pull in less data (issues seem to arise when exceeding ~300k lines at ~20 columns per line). Sometimes it'll process 500-800k lines no problem, sometimes it balks at 250k, but usually around 300-350k is where I see issues.

While the solution is simple enough to understand, implementing it for my use case involves changing a pretty large system in a lot of ways. What would really help me is understanding why this issue occurs. It's not a memory issue, it doesn't seem to be any kind of formatting or de-facto length limit issue...and it's not consistent unless I'm using the exact same set of data going in.

Any thoughts or suggestions (other than limit the number of lines/columns/items/etc going in)?

**Comment by wdavidw** [comment]
In my understanding, you're using the callback which is meant to be convenient but not scalable by design since it need to buffer the all generated text to pass it to the callback as a single variable. If you need scalability, then you must use the stream API which rely on Node.js mechanism.
